export const countries = [
    { country: "Afghanistan", postcode: "+93" },
    { country: "Åland Islands", postcode: "+358" },
    { country: "Albania", postcode: "+355" },
    { country: "Algeria", postcode: "+213" },
    { country: "American Samoa", postcode: "+1" },
    { country: "Andorra", postcode: "+376" },
    { country: "Angola", postcode: "+244" },
    { country: "Anguilla", postcode: "+1" },
    { country: "Antarctica", postcode: "+672" },
    { country: "Antigua and Barbuda", postcode: "+1" },
    { country: "Argentina", postcode: "+54" },
    { country: "Armenia", postcode: "+374" },
    { country: "Aruba", postcode: "+297" },
    { country: "Australia", postcode: "+61" },
    { country: "Austria", postcode: "+43" },
    { country: "Azerbaijan", postcode: "+994" },
    { country: "Bahamas", postcode: "+1" },
    { country: "Bahrain", postcode: "+973" },
    { country: "Bangladesh", postcode: "+880" },
    { country: "Barbados", postcode: "+1" },
    { country: "Belarus", postcode: "+375" },
    { country: "Belgium", postcode: "+32" },
    { country: "Belize", postcode: "+501" },
    { country: "Benin", postcode: "+229" },
    { country: "Bermuda", postcode: "+1" },
    { country: "Bhutan", postcode: "+975" },
    { country: "Bolivia", postcode: "+591" },
    { country: "Bosnia and Herzegovina", postcode: "+387" },
    { country: "Botswana", postcode: "+267" },
    { country: "Bouvet Island", postcode: "+55" },
    { country: "Brazil", postcode: "+55" },
    { country: "British Indian Ocean Territory", postcode: "+246" },
    { country: "Brunei Darussalam", postcode: "+673" },
    { country: "Bulgaria", postcode: "+359" },
    { country: "Burkina Faso", postcode: "+226" },
    { country: "Burundi", postcode: "+257" },
    { country: "Cambodia", postcode: "+855" },
    { country: "Cameroon", postcode: "+237" },
    { country: "Canada", postcode: "+1" },
    { country: "Cape Verde", postcode: "+238" },
    { country: "Cayman Islands", postcode: "+1" },
    { country: "Central African Republic", postcode: "+236" },
    { country: "Chad", postcode: "+235" },
    { country: "Chile", postcode: "+56" },
    { country: "China", postcode: "+86" },
    { country: "Christmas Island", postcode: "+618" },
    { country: "Cocos (Keeling) Islands", postcode: "+61" },
    { country: "Colombia", postcode: "+57" },
    { country: "Comoros", postcode: "+269" },
    { country: "Congo", postcode: "+242" },
    { country: "Democratic Republic of the Congo", postcode: "+243" },
    { country: "Cook Islands", postcode: "+682" },
    { country: "Costa Rica", postcode: "+506" },
    { country: "Côte D'Ivoire", postcode: "+225" },
    { country: "Croatia", postcode: "+385" },
    { country: "Cuba", postcode: "+53" },
    { country: "Cyprus", postcode: "+357" },
    { country: "Czech Republic", postcode: "+420" },
    { country: "Denmark", postcode: "+45" },
    { country: "Djibouti", postcode: "+253" },
    { country: "Dominica", postcode: "+1" },
    { country: "Dominican Republic", postcode: "+1" },
    { country: "Ecuador", postcode: "+593" },
    { country: "Egypt", postcode: "+20" },
    { country: "El Salvador", postcode: "+503" },
    { country: "Equatorial Guinea", postcode: "+240" },
    { country: "Eritrea", postcode: "+291" },
    { country: "Estonia", postcode: "+372" },
    { country: "Ethiopia", postcode: "+251" },
    { country: "Falkland Islands/Islas Malvinas", postcode: "+500" },
    { country: "Faroe Islands", postcode: "+298" },
    { country: "Fiji", postcode: "+679" },
    { country: "Finland", postcode: "+358" },
    { country: "France", postcode: "+33" },
    { country: "French Guiana", postcode: "+594" },
    { country: "French Polynesia", postcode: "+689" },
    { country: "French Southern Territories", postcode: "+262" },
    { country: "Gabon", postcode: "+241" },
    { country: "Gambia", postcode: "+220" },
    { country: "Georgia", postcode: "+995" },
    { country: "Germany", postcode: "+49" },
    { country: "Ghana", postcode: "+233" },
    { country: "Gibraltar", postcode: "+350" },
    { country: "Greece", postcode: "+30" },
    { country: "Greenland", postcode: "+299" },
    { country: "Grenada", postcode: "+1" },
    { country: "Guadeloupe", postcode: "+590" },
    { country: "Guam", postcode: "+1" },
    { country: "Guatemala", postcode: "+502" },
    { country: "Guernsey", postcode: "+44" },
    { country: "Guinea", postcode: "+224" },
    { country: "Guinea-Bissau", postcode: "+245" },
    { country: "Guyana", postcode: "+592" },
    { country: "Haiti", postcode: "+509" },
    { country: "Heard Island and McDonald Islands", postcode: "+672" },
    { country: "Vatican City", postcode: "+39" },
    { country: "Honduras", postcode: "+504" },
    { country: "Hong Kong", postcode: "+852" },
    { country: "Hungary", postcode: "+36" },
    { country: "Iceland", postcode: "+354" },
    { country: "India", postcode: "+91" },
    { country: "Indonesia", postcode: "+62" },
    { country: "Iran", postcode: "+98" },
    { country: "Iraq", postcode: "+964" },
    { country: "Republic of Ireland", postcode: "+353" },
    { country: "Isle of Man", postcode: "+44" },
    { country: "Israel", postcode: "+972" },
    { country: "Italy", postcode: "+39" },
    { country: "Jamaica", postcode: "+1" },
    { country: "Japan", postcode: "+81" },
    { country: "Jersey", postcode: "+44" },
    { country: "Jordan", postcode: "+962" },
    { country: "Kazakhstan", postcode: "+7" },
    { country: "Kenya", postcode: "+254" },
    { country: "Kiribati", postcode: "+686" },
    { country: "North Korea", postcode: "+850" },
    { country: "South Korea", postcode: "+82" },
    { country: "Kuwait", postcode: "+965" },
    { country: "Kyrgyzstan", postcode: "+996" },
    { country: "Laos", postcode: "+856" },
    { country: "Latvia", postcode: "+371" },
    { country: "Lebanon", postcode: "+961" },
    { country: "Lesotho", postcode: "+266" },
    { country: "Liberia", postcode: "+231" },
    { country: "Libya", postcode: "+218" },
    { country: "Liechtenstein", postcode: "+423" },
    { country: "Lithuania", postcode: "+370" },
    { country: "Luxembourg", postcode: "+352" },
    { country: "Macau", postcode: "+853" },
    { country: "Republic of Macedonia", postcode: "+389" },
    { country: "Madagascar", postcode: "+261" },
    { country: "Malawi", postcode: "+265" },
    { country: "Malaysia", postcode: "+60" },
    { country: "Maldives", postcode: "+960" },
    { country: "Mali", postcode: "+223" },
    { country: "Malta", postcode: "+356" },
    { country: "Marshall Islands", postcode: "+692" },
    { country: "Martinique", postcode: "+596" },
    { country: "Mauritania", postcode: "+222" },
    { country: "Mauritius", postcode: "+230" },
    { country: "Mayotte", postcode: "+269" },
    { country: "Mexico", postcode: "+52" },
    { country: "Federated States of Micronesia", postcode: "+691" },
    { country: "Moldova", postcode: "+373" },
    { country: "Monaco", postcode: "+377" },
    { country: "Mongolia", postcode: "+976" },
    { country: "Montenegro", postcode: "+382" },
    { country: "Montserrat", postcode: "+1" },
    { country: "Morocco", postcode: "+212" },
    { country: "Mozambique", postcode: "+258" },
    { country: "Myanmar", postcode: "+95" },
    { country: "Namibia", postcode: "+264" },
    { country: "Nauru", postcode: "+674" },
    { country: "Nepal", postcode: "+977" },
    { country: "Netherlands", postcode: "+31" },
    { country: "Netherlands Antilles", postcode: "+599" },
    { country: "New Caledonia", postcode: "+687" },
    { country: "New Zealand", postcode: "+64" },
    { country: "Nicaragua", postcode: "+505" },
    { country: "Niger", postcode: "+227" },
    { country: "Nigeria", postcode: "+234" },
    { country: "Niue", postcode: "+683" },
    { country: "Norfolk Island", postcode: "+672" },
    { country: "Northern Mariana Islands", postcode: "+1" },
    { country: "Norway", postcode: "+47" },
    { country: "Oman", postcode: "+968" },
    { country: "Pakistan", postcode: "+92" },
    { country: "Palau", postcode: "+680" },
    { country: "Palestinian Territory, Occupied", postcode: "+970" },
    { country: "Panama", postcode: "+507" },
    { country: "Papua New Guinea", postcode: "+675" },
    { country: "Paraguay", postcode: "+595" },
    { country: "Peru", postcode: "+51" },
    { country: "Philippines", postcode: "+63" },
    { country: "Pitcairn Islands", postcode: "+872" },
    { country: "Poland", postcode: "+48" },
    { country: "Portugal", postcode: "+351" },
    { country: "Puerto Rico", postcode: "+1" },
    { country: "Qatar", postcode: "+974" },
    { country: "Réunion", postcode: "+262" },
    { country: "Romania", postcode: "+40" },
    { country: "Russia", postcode: "+7" },
    { country: "Rwanda", postcode: "+250" },
    { country: "Saint Barthelemy", postcode: "+590" },
    { country: "Saint Helena", postcode: "+290" },
    { country: "Saint Kitts and Nevis", postcode: "+1" },
    { country: "Saint Lucia", postcode: "+1" },
    { country: "Saint Martin", postcode: "+590" },
    { country: "Saint Pierre and Miquelon", postcode: "+508" },
    { country: "Saint Vincent and the Grenadines", postcode: "+1" },
    { country: "Samoa", postcode: "+685" },
    { country: "San Marino", postcode: "+378" },
    { country: "São Tomé and Príncipe", postcode: "+239" },
    { country: "Saudi Arabia", postcode: "+966" },
    { country: "Senegal", postcode: "+221" },
    { country: "Serbia", postcode: "+381" },
    { country: "Seychelles", postcode: "+248" },
    { country: "Sierra Leone", postcode: "+232" },
    { country: "Singapore", postcode: "+65" },
    { country: "Slovakia", postcode: "+421" },
    { country: "Slovenia", postcode: "+386" },
    { country: "Solomon Islands", postcode: "+677" },
    { country: "Somalia", postcode: "+252" },
    { country: "South Africa", postcode: "+27" },
    { country: "South Georgia and the South Sandwich Islands", postcode: "+500" },
    { country: "Spain", postcode: "+34" },
    { country: "Sri Lanka", postcode: "+94" },
    { country: "Sudan", postcode: "+249" },
    { country: "Suriname", postcode: "+597" },
    { country: "Svalbard", postcode: "+47" },
    { country: "Swaziland", postcode: "+268" },
    { country: "Sweden", postcode: "+46" },
    { country: "Switzerland", postcode: "+41" },
    { country: "Syria", postcode: "+963" },
    { country: "Taiwan", postcode: "+886" },
    { country: "Tajikistan", postcode: "+992" },
    { country: "Tanzania", postcode: "+255" },
    { country: "Thailand", postcode: "+66" },
    { country: "Timor-Leste", postcode: "+670" },
    { country: "Togo", postcode: "+228" },
    { country: "Tokelau", postcode: "+690" },
    { country: "Tonga", postcode: "+676" },
    { country: "Trinidad and Tobago", postcode: "+1" },
    { country: "Tunisia", postcode: "+216" },
    { country: "Turkey", postcode: "+90" },
    { country: "Turkmenistan", postcode: "+993" },
    { country: "Turks and Caicos Islands", postcode: "+1" },
    { country: "Tuvalu", postcode: "+688" },
    { country: "Republic of Uganda", postcode: "+256" },
    { country: "Ukraine", postcode: "+380" },
    { country: "United Arab Emirates", postcode: "+971" },
    { country: "United Kingdom", postcode: "+44" },
    { country: "United States", postcode: "+1" },
    { country: "United States Minor Outlying", postcode: "+1" },
    { country: "Uruguay", postcode: "+598" },
    { country: "Uzbekistan", postcode: "+998" },
    { country: "Vanuatu", postcode: "+678" },
    { country: "Venezuela", postcode: "+58" },
    { country: "Vietnam", postcode: "+84" },
    { country: "British Virgin Islands", postcode: "+1" },
    { country: "U.S. Virgin Islands", postcode: "+1" },
    { country: "Wallis and Futuna", postcode: "+681" },
    { country: "Western Sahara", postcode: "+212" },
    { country: "Yemen", postcode: "+967" },
    { country: "Zambia", postcode: "+260" },
    { country: "Zimbabwe", postcode: "+263" },
    { country: "Tobago", postcode: "+1" },
  ];