export enum SettingKeys {
    TITLE = "TITLE",
    LOGO_URL = "LOGO_URL",
    USE_MENU_CATEGORY = "USE_MENU_CATEGORY",
    ADMIN_MENU = "ADMIN_MENU",
    EDITOR_MENU = "EDITOR_MENU",
    MENU_CATEGORIES = "MENU_CATEGORIES"
}
