// TODO: Mark here https://react-icons.github.io/react-icons/icons?name=fc
import * as DefaultIcon from "react-icons/fc";

const NextIcon = ({
  Icon = DefaultIcon,
  name,
  className,
}: {
  Icon?: any;
  name: string;
  className?: string;
}) => {
  const NIcon = Icon[name] || Icon["FcAnswers"];
  return <NIcon className={className} />;
};

export default NextIcon;

export const FCIconData = [
  "FcAbout",
  "FcAcceptDatabase",
  "FcAddColumn",
  "FcAddDatabase",
  "FcAddImage",
  "FcAddRow",
  "FcAddressBook",
  "FcAdvance",
  "FcAdvertising",
  "FcAlarmClock",
  "FcAlphabeticalSortingAz",
  "FcAlphabeticalSortingZa",
  "FcAndroidOs",
  "FcAnswers",
  "FcApproval",
  "FcApprove",
  "FcAreaChart",
  "FcAssistant",
  "FcAudioFile",
  "FcAutomatic",
  "FcAutomotive",
  "FcBadDecision",
  "FcBarChart",
  "FcBbc",
  "FcBearish",
  "FcBinoculars",
  "FcBiohazard",
  "FcBiomass",
  "FcBiotech",
  "FcBookmark",
  "FcBriefcase",
  "FcBrokenLink",
  "FcBullish",
  "FcBusinessContact",
  "FcBusiness",
  "FcBusinessman",
  "FcBusinesswoman",
  "FcButtingIn",
  "FcCableRelease",
  "FcCalculator",
  "FcCalendar",
  "FcCallTransfer",
  "FcCallback",
  "FcCamcorderPro",
  "FcCamcorder",
  "FcCameraAddon",
  "FcCameraIdentification",
  "FcCamera",
  "FcCancel",
  "FcCandleSticks",
  "FcCapacitor",
  "FcCdLogo",
  "FcCellPhone",
  "FcChargeBattery",
  "FcCheckmark",
  "FcCircuit",
  "FcClapperboard",
  "FcClearFilters",
  "FcClock",
  "FcCloseUpMode",
  "FcCloth",
  "FcCollaboration",
  "FcCollapse",
  "FcCollect",
  "FcComboChart",
  "FcCommandLine",
  "FcComments",
  "FcCompactCamera",
  "FcConferenceCall",
  "FcContacts",
  "FcCopyleft",
  "FcCopyright",
  "FcCrystalOscillator",
  "FcCurrencyExchange",
  "FcCursor",
  "FcCustomerSupport",
  "FcDam",
  "FcDataBackup",
  "FcDataConfiguration",
  "FcDataEncryption",
  "FcDataProtection",
  "FcDataRecovery",
  "FcDataSheet",
  "FcDatabase",
  "FcDebian",
  "FcDebt",
  "FcDecision",
  "FcDeleteColumn",
  "FcDeleteDatabase",
  "FcDeleteRow",
  "FcDepartment",
  "FcDeployment",
  "FcDiploma1",
  "FcDiploma2",
  "FcDisapprove",
  "FcDisclaimer",
  "FcDislike",
  "FcDisplay",
  "FcDoNotInhale",
  "FcDoNotInsert",
  "FcDoNotMix",
  "FcDocument",
  "FcDonate",
  "FcDoughnutChart",
  "FcDownLeft",
  "FcDownRight",
  "FcDown",
  "FcDownload",
  "FcDribbble",
  "FcDvdLogo",
  "FcEditImage",
  "FcElectricalSensor",
  "FcElectricalThreshold",
  "FcElectricity",
  "FcElectroDevices",
  "FcElectronics",
  "FcEmptyBattery",
  "FcEmptyFilter",
  "FcEmptyTrash",
  "FcEndCall",
  "FcEngineering",
  "FcEnteringHeavenAlive",
  "FcExpand",
  "FcExpired",
  "FcExport",
  "FcExternal",
  "FcFactoryBreakdown",
  "FcFactory",
  "FcFaq",
  "FcFeedIn",
  "FcFeedback",
  "FcFile",
  "FcFilingCabinet",
  "FcFilledFilter",
  "FcFilmReel",
  "FcFilm",
  "FcFinePrint",
  "FcFlashAuto",
  "FcFlashOff",
  "FcFlashOn",
  "FcFlowChart",
  "FcFolder",
  "FcFrame",
  "FcFullBattery",
  "FcFullTrash",
  "FcGallery",
  "FcGenealogy",
  "FcGenericSortingAsc",
  "FcGenericSortingDesc",
  "FcGlobe",
  "FcGoodDecision",
  "FcGoogle",
  "FcGraduationCap",
  "FcGrid",
  "FcHeadset",
  "FcHeatMap",
  "FcHighBattery",
  "FcHighPriority",
  "FcHome",
  "FcIcons8Cup",
  "FcIdea",
  "FcImageFile",
  "FcImport",
  "FcInTransit",
  "FcInfo",
  "FcInspection",
  "FcIntegratedWebcam",
  "FcInternal",
  "FcInvite",
  "FcIpad",
  "FcIphone",
  "FcKey",
  "FcKindle",
  "FcLandscape",
  "FcLeave",
  "FcLeftDown",
  "FcLeftDown2",
  "FcLeftUp",
  "FcLeftUp2",
  "FcLeft",
  "FcLibrary",
  "FcLightAtTheEndOfTunnel",
  "FcLikePlaceholder",
  "FcLike",
  "FcLineChart",
  "FcLink",
  "FcLinux",
  "FcList",
  "FcLockLandscape",
  "FcLockPortrait",
  "FcLock",
  "FcLowBattery",
  "FcLowPriority",
  "FcMakeDecision",
  "FcManager",
  "FcMediumPriority",
  "FcMenu",
  "FcMiddleBattery",
  "FcMindMap",
  "FcMinus",
  "FcMissedCall",
  "FcMms",
  "FcMoneyTransfer",
  "FcMultipleCameras",
  "FcMultipleDevices",
  "FcMultipleInputs",
  "FcMultipleSmartphones",
  "FcMusic",
  "FcNegativeDynamic",
  "FcNeutralDecision",
  "FcNeutralTrading",
  "FcNews",
  "FcNext",
  "FcNfcSign",
  "FcNightLandscape",
  "FcNightPortrait",
  "FcNoIdea",
  "FcNoVideo",
  "FcNook",
  "FcNumericalSorting12",
  "FcNumericalSorting21",
  "FcOk",
  "FcOldTimeCamera",
  "FcOnlineSupport",
  "FcOpenedFolder",
  "FcOrgUnit",
  "FcOrganization",
  "FcOvertime",
  "FcPackage",
  "FcPaid",
  "FcPanorama",
  "FcParallelTasks",
  "FcPhoneAndroid",
  "FcPhone",
  "FcPhotoReel",
  "FcPicture",
  "FcPieChart",
  "FcPlanner",
  "FcPlus",
  "FcPodiumWithAudience",
  "FcPodiumWithSpeaker",
  "FcPodiumWithoutSpeaker",
  "FcPortraitMode",
  "FcPositiveDynamic",
  "FcPrevious",
  "FcPrint",
  "FcPrivacy",
  "FcProcess",
  "FcPuzzle",
  "FcQuestions",
  "FcRadarPlot",
  "FcRating",
  "FcRatings",
  "FcReadingEbook",
  "FcReading",
  "FcReddit",
  "FcRedo",
  "FcRefresh",
  "FcRegisteredTrademark",
  "FcRemoveImage",
  "FcReuse",
  "FcRightDown",
  "FcRightDown2",
  "FcRightUp",
  "FcRightUp2",
  "FcRight",
  "FcRotateCamera",
  "FcRotateToLandscape",
  "FcRotateToPortrait",
  "FcRuler",
  "FcRules",
  "FcSafe",
  "FcSalesPerformance",
  "FcScatterPlot",
  "FcSearch",
  "FcSelfServiceKiosk",
  "FcSelfie",
  "FcSerialTasks",
  "FcServiceMark",
  "FcServices",
  "FcSettings",
  "FcShare",
  "FcShipped",
  "FcShop",
  "FcSignature",
  "FcSimCardChip",
  "FcSimCard",
  "FcSlrBackSide",
  "FcSmartphoneTablet",
  "FcSms",
  "FcSoundRecordingCopyright",
  "FcSpeaker",
  "FcSportsMode",
  "FcStackOfPhotos",
  "FcStart",
  "FcStatistics",
  "FcSteam",
  "FcStumbleupon",
  "FcSupport",
  "FcSurvey",
  "FcSwitchCamera",
  "FcSynchronize",
  "FcTabletAndroid",
  "FcTemplate",
  "FcTimeline",
  "FcTodoList",
  "FcTouchscreenSmartphone",
  "FcTrademark",
  "FcTreeStructure",
  "FcTwoSmartphones",
  "FcUndo",
  "FcUnlock",
  "FcUpLeft",
  "FcUpRight",
  "FcUp",
  "FcUpload",
  "FcUsb",
  "FcVideoCall",
  "FcVideoFile",
  "FcVideoProjector",
  "FcViewDetails",
  "FcVip",
  "FcVlc",
  "FcVoicePresentation",
  "FcVoicemail",
  "FcWebcam",
  "FcWiFiLogo",
  "FcWikipedia",
  "FcWorkflow",
];

export enum FCIcons {
  FcAbout = "FcAbout",
  FcAcceptDatabase = "FcAcceptDatabase",
  FcAddColumn = "FcAddColumn",
  FcAddDatabase = "FcAddDatabase",
  FcAddImage = "FcAddImage",
  FcAddRow = "FcAddRow",
  FcAddressBook = "FcAddressBook",
  FcAdvance = "FcAdvance",
  FcAdvertising = "FcAdvertising",
  FcAlarmClock = "FcAlarmClock",
  FcAlphabeticalSortingAz = "FcAlphabeticalSortingAz",
  FcAlphabeticalSortingZa = "FcAlphabeticalSortingZa",
  FcAndroidOs = "FcAndroidOs",
  FcAnswers = "FcAnswers",
  FcApproval = "FcApproval",
  FcApprove = "FcApprove",
  FcAreaChart = "FcAreaChart",
  FcAssistant = "FcAssistant",
  FcAudioFile = "FcAudioFile",
  FcAutomatic = "FcAutomatic",
  FcAutomotive = "FcAutomotive",
  FcBadDecision = "FcBadDecision",
  FcBarChart = "FcBarChart",
  FcBbc = "FcBbc",
  FcBearish = "FcBearish",
  FcBinoculars = "FcBinoculars",
  FcBiohazard = "FcBiohazard",
  FcBiomass = "FcBiomass",
  FcBiotech = "FcBiotech",
  FcBookmark = "FcBookmark",
  FcBriefcase = "FcBriefcase",
  FcBrokenLink = "FcBrokenLink",
  FcBullish = "FcBullish",
  FcBusinessContact = "FcBusinessContact",
  FcBusiness = "FcBusiness",
  FcBusinessman = "FcBusinessman",
  FcBusinesswoman = "FcBusinesswoman",
  FcButtingIn = "FcButtingIn",
  FcCableRelease = "FcCableRelease",
  FcCalculator = "FcCalculator",
  FcCalendar = "FcCalendar",
  FcCallTransfer = "FcCallTransfer",
  FcCallback = "FcCallback",
  FcCamcorderPro = "FcCamcorderPro",
  FcCamcorder = "FcCamcorder",
  FcCameraAddon = "FcCameraAddon",
  FcCameraIdentification = "FcCameraIdentification",
  FcCamera = "FcCamera",
  FcCancel = "FcCancel",
  FcCandleSticks = "FcCandleSticks",
  FcCapacitor = "FcCapacitor",
  FcCdLogo = "FcCdLogo",
  FcCellPhone = "FcCellPhone",
  FcChargeBattery = "FcChargeBattery",
  FcCheckmark = "FcCheckmark",
  FcCircuit = "FcCircuit",
  FcClapperboard = "FcClapperboard",
  FcClearFilters = "FcClearFilters",
  FcClock = "FcClock",
  FcCloseUpMode = "FcCloseUpMode",
  FcCloth = "FcCloth",
  FcCollaboration = "FcCollaboration",
  FcCollapse = "FcCollapse",
  FcCollect = "FcCollect",
  FcComboChart = "FcComboChart",
  FcCommandLine = "FcCommandLine",
  FcComments = "FcComments",
  FcCompactCamera = "FcCompactCamera",
  FcConferenceCall = "FcConferenceCall",
  FcContacts = "FcContacts",
  FcCopyleft = "FcCopyleft",
  FcCopyright = "FcCopyright",
  FcCrystalOscillator = "FcCrystalOscillator",
  FcCurrencyExchange = "FcCurrencyExchange",
  FcCursor = "FcCursor",
  FcCustomerSupport = "FcCustomerSupport",
  FcDam = "FcDam",
  FcDataBackup = "FcDataBackup",
  FcDataConfiguration = "FcDataConfiguration",
  FcDataEncryption = "FcDataEncryption",
  FcDataProtection = "FcDataProtection",
  FcDataRecovery = "FcDataRecovery",
  FcDataSheet = "FcDataSheet",
  FcDatabase = "FcDatabase",
  FcDebian = "FcDebian",
  FcDebt = "FcDebt",
  FcDecision = "FcDecision",
  FcDeleteColumn = "FcDeleteColumn",
  FcDeleteDatabase = "FcDeleteDatabase",
  FcDeleteRow = "FcDeleteRow",
  FcDepartment = "FcDepartment",
  FcDeployment = "FcDeployment",
  FcDiploma1 = "FcDiploma1",
  FcDiploma2 = "FcDiploma2",
  FcDisapprove = "FcDisapprove",
  FcDisclaimer = "FcDisclaimer",
  FcDislike = "FcDislike",
  FcDisplay = "FcDisplay",
  FcDoNotInhale = "FcDoNotInhale",
  FcDoNotInsert = "FcDoNotInsert",
  FcDoNotMix = "FcDoNotMix",
  FcDocument = "FcDocument",
  FcDonate = "FcDonate",
  FcDoughnutChart = "FcDoughnutChart",
  FcDownLeft = "FcDownLeft",
  FcDownRight = "FcDownRight",
  FcDown = "FcDown",
  FcDownload = "FcDownload",
  FcDribbble = "FcDribbble",
  FcDvdLogo = "FcDvdLogo",
  FcEditImage = "FcEditImage",
  FcElectricalSensor = "FcElectricalSensor",
  FcElectricalThreshold = "FcElectricalThreshold",
  FcElectricity = "FcElectricity",
  FcElectroDevices = "FcElectroDevices",
  FcElectronics = "FcElectronics",
  FcEmptyBattery = "FcEmptyBattery",
  FcEmptyFilter = "FcEmptyFilter",
  FcEmptyTrash = "FcEmptyTrash",
  FcEndCall = "FcEndCall",
  FcEngineering = "FcEngineering",
  FcEnteringHeavenAlive = "FcEnteringHeavenAlive",
  FcExpand = "FcExpand",
  FcExpired = "FcExpired",
  FcExport = "FcExport",
  FcExternal = "FcExternal",
  FcFactoryBreakdown = "FcFactoryBreakdown",
  FcFactory = "FcFactory",
  FcFaq = "FcFaq",
  FcFeedIn = "FcFeedIn",
  FcFeedback = "FcFeedback",
  FcFile = "FcFile",
  FcFilingCabinet = "FcFilingCabinet",
  FcFilledFilter = "FcFilledFilter",
  FcFilmReel = "FcFilmReel",
  FcFilm = "FcFilm",
  FcFinePrint = "FcFinePrint",
  FcFlashAuto = "FcFlashAuto",
  FcFlashOff = "FcFlashOff",
  FcFlashOn = "FcFlashOn",
  FcFlowChart = "FcFlowChart",
  FcFolder = "FcFolder",
  FcFrame = "FcFrame",
  FcFullBattery = "FcFullBattery",
  FcFullTrash = "FcFullTrash",
  FcGallery = "FcGallery",
  FcGenealogy = "FcGenealogy",
  FcGenericSortingAsc = "FcGenericSortingAsc",
  FcGenericSortingDesc = "FcGenericSortingDesc",
  FcGlobe = "FcGlobe",
  FcGoodDecision = "FcGoodDecision",
  FcGoogle = "FcGoogle",
  FcGraduationCap = "FcGraduationCap",
  FcGrid = "FcGrid",
  FcHeadset = "FcHeadset",
  FcHeatMap = "FcHeatMap",
  FcHighBattery = "FcHighBattery",
  FcHighPriority = "FcHighPriority",
  FcHome = "FcHome",
  FcIcons8Cup = "FcIcons8Cup",
  FcIdea = "FcIdea",
  FcImageFile = "FcImageFile",
  FcImport = "FcImport",
  FcInTransit = "FcInTransit",
  FcInfo = "FcInfo",
  FcInspection = "FcInspection",
  FcIntegratedWebcam = "FcIntegratedWebcam",
  FcInternal = "FcInternal",
  FcInvite = "FcInvite",
  FcIpad = "FcIpad",
  FcIphone = "FcIphone",
  FcKey = "FcKey",
  FcKindle = "FcKindle",
  FcLandscape = "FcLandscape",
  FcLeave = "FcLeave",
  FcLeftDown = "FcLeftDown",
  FcLeftDown2 = "FcLeftDown2",
  FcLeftUp = "FcLeftUp",
  FcLeftUp2 = "FcLeftUp2",
  FcLeft = "FcLeft",
  FcLibrary = "FcLibrary",
  FcLightAtTheEndOfTunnel = "FcLightAtTheEndOfTunnel",
  FcLikePlaceholder = "FcLikePlaceholder",
  FcLike = "FcLike",
  FcLineChart = "FcLineChart",
  FcLink = "FcLink",
  FcLinux = "FcLinux",
  FcList = "FcList",
  FcLockLandscape = "FcLockLandscape",
  FcLockPortrait = "FcLockPortrait",
  FcLock = "FcLock",
  FcLowBattery = "FcLowBattery",
  FcLowPriority = "FcLowPriority",
  FcMakeDecision = "FcMakeDecision",
  FcManager = "FcManager",
  FcMediumPriority = "FcMediumPriority",
  FcMenu = "FcMenu",
  FcMiddleBattery = "FcMiddleBattery",
  FcMindMap = "FcMindMap",
  FcMinus = "FcMinus",
  FcMissedCall = "FcMissedCall",
  FcMms = "FcMms",
  FcMoneyTransfer = "FcMoneyTransfer",
  FcMultipleCameras = "FcMultipleCameras",
  FcMultipleDevices = "FcMultipleDevices",
  FcMultipleInputs = "FcMultipleInputs",
  FcMultipleSmartphones = "FcMultipleSmartphones",
  FcMusic = "FcMusic",
  FcNegativeDynamic = "FcNegativeDynamic",
  FcNeutralDecision = "FcNeutralDecision",
  FcNeutralTrading = "FcNeutralTrading",
  FcNews = "FcNews",
  FcNext = "FcNext",
  FcNfcSign = "FcNfcSign",
  FcNightLandscape = "FcNightLandscape",
  FcNightPortrait = "FcNightPortrait",
  FcNoIdea = "FcNoIdea",
  FcNoVideo = "FcNoVideo",
  FcNook = "FcNook",
  FcNumericalSorting12 = "FcNumericalSorting12",
  FcNumericalSorting21 = "FcNumericalSorting21",
  FcOk = "FcOk",
  FcOldTimeCamera = "FcOldTimeCamera",
  FcOnlineSupport = "FcOnlineSupport",
  FcOpenedFolder = "FcOpenedFolder",
  FcOrgUnit = "FcOrgUnit",
  FcOrganization = "FcOrganization",
  FcOvertime = "FcOvertime",
  FcPackage = "FcPackage",
  FcPaid = "FcPaid",
  FcPanorama = "FcPanorama",
  FcParallelTasks = "FcParallelTasks",
  FcPhoneAndroid = "FcPhoneAndroid",
  FcPhone = "FcPhone",
  FcPhotoReel = "FcPhotoReel",
  FcPicture = "FcPicture",
  FcPieChart = "FcPieChart",
  FcPlanner = "FcPlanner",
  FcPlus = "FcPlus",
  FcPodiumWithAudience = "FcPodiumWithAudience",
  FcPodiumWithSpeaker = "FcPodiumWithSpeaker",
  FcPodiumWithoutSpeaker = "FcPodiumWithoutSpeaker",
  FcPortraitMode = "FcPortraitMode",
  FcPositiveDynamic = "FcPositiveDynamic",
  FcPrevious = "FcPrevious",
  FcPrint = "FcPrint",
  FcPrivacy = "FcPrivacy",
  FcProcess = "FcProcess",
  FcPuzzle = "FcPuzzle",
  FcQuestions = "FcQuestions",
  FcRadarPlot = "FcRadarPlot",
  FcRating = "FcRating",
  FcRatings = "FcRatings",
  FcReadingEbook = "FcReadingEbook",
  FcReading = "FcReading",
  FcReddit = "FcReddit",
  FcRedo = "FcRedo",
  FcRefresh = "FcRefresh",
  FcRegisteredTrademark = "FcRegisteredTrademark",
  FcRemoveImage = "FcRemoveImage",
  FcReuse = "FcReuse",
  FcRightDown = "FcRightDown",
  FcRightDown2 = "FcRightDown2",
  FcRightUp = "FcRightUp",
  FcRightUp2 = "FcRightUp2",
  FcRight = "FcRight",
  FcRotateCamera = "FcRotateCamera",
  FcRotateToLandscape = "FcRotateToLandscape",
  FcRotateToPortrait = "FcRotateToPortrait",
  FcRuler = "FcRuler",
  FcRules = "FcRules",
  FcSafe = "FcSafe",
  FcSalesPerformance = "FcSalesPerformance",
  FcScatterPlot = "FcScatterPlot",
  FcSearch = "FcSearch",
  FcSelfServiceKiosk = "FcSelfServiceKiosk",
  FcSelfie = "FcSelfie",
  FcSerialTasks = "FcSerialTasks",
  FcServiceMark = "FcServiceMark",
  FcServices = "FcServices",
  FcSettings = "FcSettings",
  FcShare = "FcShare",
  FcShipped = "FcShipped",
  FcShop = "FcShop",
  FcSignature = "FcSignature",
  FcSimCardChip = "FcSimCardChip",
  FcSimCard = "FcSimCard",
  FcSlrBackSide = "FcSlrBackSide",
  FcSmartphoneTablet = "FcSmartphoneTablet",
  FcSms = "FcSms",
  FcSoundRecordingCopyright = "FcSoundRecordingCopyright",
  FcSpeaker = "FcSpeaker",
  FcSportsMode = "FcSportsMode",
  FcStackOfPhotos = "FcStackOfPhotos",
  FcStart = "FcStart",
  FcStatistics = "FcStatistics",
  FcSteam = "FcSteam",
  FcStumbleupon = "FcStumbleupon",
  FcSupport = "FcSupport",
  FcSurvey = "FcSurvey",
  FcSwitchCamera = "FcSwitchCamera",
  FcSynchronize = "FcSynchronize",
  FcTabletAndroid = "FcTabletAndroid",
  FcTemplate = "FcTemplate",
  FcTimeline = "FcTimeline",
  FcTodoList = "FcTodoList",
  FcTouchscreenSmartphone = "FcTouchscreenSmartphone",
  FcTrademark = "FcTrademark",
  FcTreeStructure = "FcTreeStructure",
  FcTwoSmartphones = "FcTwoSmartphones",
  FcUndo = "FcUndo",
  FcUnlock = "FcUnlock",
  FcUpLeft = "FcUpLeft",
  FcUpRight = "FcUpRight",
  FcUp = "FcUp",
  FcUpload = "FcUpload",
  FcUsb = "FcUsb",
  FcVideoCall = "FcVideoCall",
  FcVideoFile = "FcVideoFile",
  FcVideoProjector = "FcVideoProjector",
  FcViewDetails = "FcViewDetails",
  FcVip = "FcVip",
  FcVlc = "FcVlc",
  FcVoicePresentation = "FcVoicePresentation",
  FcVoicemail = "FcVoicemail",
  FcWebcam = "FcWebcam",
  FcWiFiLogo = "FcWiFiLogo",
  FcWikipedia = "FcWikipedia",
  FcWorkflow = "FcWorkflow",
}
