export const ROLES = {
  ADMIN: "ADMIN",
  EDITOR:"EDITOR",
  MEMBER: "MEMBER",
  PARTNER: "PARTNER",
  ADMIN_EDITOR: ["ADMIN", "EDITOR"],
  ADMIN_USER: ["ADMIN", "USER"],
  ADMIN_USER_PARTNER: ["ADMIN", "USER", "PARTNER"]
};
